// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://inrscavonzaqqjbvawtd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlucnNjYXZvbnphcXFqYnZhd3RkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4Mzg5NDcsImV4cCI6MjA2ODQxNDk0N30.GHVQeopm1RdgyibjuwvFG4pHmsfZj24skwGRm9Dv8VQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});